### ISSUE TITLE
Validation results of reviewed=false causes `jpm sign` to time out

### ISSUE THREAD

**Issue by kumar303** [mozilla-jetpack/jpm#375]
If you put `eval()` somewhere in the add-on it will trigger this state.

Example:
````
$ jpm sign --api-key ... --api-secret ... --api-url-prefix https://addons.allizom.org/en-US/firefox/api/v3
JPM [info] Starting jpm sign on GitHub Tab Width
Creating XPI
JPM [info] XPI created at /Users/kumar/dev/gh-tab-width/@gh-tab-width-0.0.58.xpi (34ms)
Created XPI at /Users/kumar/dev/gh-tab-width/@gh-tab-width-0.0.58.xpi
Successfully created xpi at /Users/kumar/dev/gh-tab-width/@gh-tab-width-0.0.58.xpi
Validating add-on [.........................................................................................................................................................................................................................................................]
Potentially unhandled rejection [2] Error: Validation took too long to complete; last status: {"active":false,"url":"https://addons.allizom.org/en-US/firefox/api/v3/addons/%40gh-tab-width/versions/0.0.58/","files":[],"passed_review":false,"processed":true,"reviewed":false,"valid":true,"validation_results":{"errors":0,"success":false,"warnings":2,"compatibility_summary":{"notices":0,"errors":0,"warnings":0},"passed_auto_validation":false,"ending_tier":5,"messages":[{"file":"bootstrap.js","editors_only":false,"description":"Access to the `Components` property is deprecated for security or ...
    at null._onTimeout (/Users/kumar/dev/jpm/lib/amo-client.js:154:14)
    at Timer.listOnTimeout (timers.js:110:15)
````

**Comment by kumar303** [comment]
We closed this because I hadn't seen the error recently. There have been a
lot of improvements so I think it's fixed. We'll reopen it if it happens
again.
