### ISSUE TITLE
package.json parse errors should point to the actual file

### ISSUE THREAD

**Issue by kumar303** [mozilla-jetpack/jpm#392]
When there's a parse error in your own package.json the error should point to the file so you can fix it. Otherwise, it's not very clear where the parse error is. This might be confused for a `jpm` bug.

Example of the output you get with `jpm sign` but this uses the shared `getManifest()` so output should be similar for other commands:
````
zenith:gh-tab-width kumar$ jpm sign --api-key ... --api-secret ...
FAIL
Error: Could not parse `package.json` file.

Unexpected token

    at /Users/kumar/dev/jpm/lib/validate.js:19:16
    at Array.forEach (native)
    at /Users/kumar/dev/jpm/lib/validate.js:17:25
    at init (/Users/kumar/dev/jpm/node_modules/when/lib/makePromise.js:39:5)
    at new Promise (/Users/kumar/dev/jpm/node_modules/when/lib/makePromise.js:27:53)
    at Function.promise (/Users/kumar/dev/jpm/node_modules/when/when.js:98:10)
    at validate (/Users/kumar/dev/jpm/lib/validate.js:16:15)
    at /Users/kumar/dev/jpm/lib/xpi.js:52:16
    at tryCatchReject (/Users/kumar/dev/jpm/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/kumar/dev/jpm/node_modules/when/lib/makePromise.js:804:4)
````

Note how my actual add-on's `package.json` file isn't in the stack trace.

**Comment by akarineb** [comment]
@kumar303 I just had this same problem 

"Error: Could not parse `package.json` file.

ENOENT: no such file or directory, open 'C:\Users\AnaKarine\package.json'"


how can I fix this?

**Comment by kumar303** [comment]
@akarineb that looks like an unrelated error to me. You should be running `jpm` within the directory of your add-on. It looks like you were running `jpm` from your home directory. However, the error for this should make it more clear.

**Comment by kumar303** [comment]
@akarineb I filed https://github.com/mozilla-jetpack/jpm/issues/530 to improve the error message.
