### ISSUE TITLE
jpm sign: error in cleanup

### ISSUE THREAD

**Issue by ianb** [mozilla-jetpack/jpm#405]
Running jpm sign with a built xpi, I get this error:

```
pageshot$ ./node_modules/.bin/jpm sign --api-key=$JWT_ISSUER --api-secret=JWT_SECRET --xpi build/mozilla-pageshot.xpi 
JPM [error] FAIL
Error: ENOENT, no such file or directory '/var/folders/s1/_n1lq3456n78ybs20hd278l40000gn/T/tmp-832271f5WBPCatCCR/data/framescripts'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at _rmdirRecursiveSync (/Users/ianbicking/src/pageshot/node_modules/tmp/lib/tmp.js:285:18)
    at Object._cleanupCallback [as remove] (/Users/ianbicking/src/pageshot/node_modules/tmp/lib/tmp.js:413:5)
    at /Users/ianbicking/src/pageshot/node_modules/jpm/lib/utils.js:142:12
    at tryCatchReject (/Users/ianbicking/src/pageshot/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/ianbicking/src/pageshot/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/ianbicking/src/pageshot/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/Users/ianbicking/src/pageshot/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/ianbicking/src/pageshot/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/ianbicking/src/pageshot/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by kumar303** [comment]
Hey Ian, thanks for the bug report. It looks like something only in your add-on is triggering this but I was able to check out the source, build an XPI, and reproduce it so I should have a fix soon.

**Comment by kumar303** [comment]
It looks like it was just a bug in the `tmp` module (the XPI gets extracted to a temp dir so `package.json` can be read). Upgrading `tmp` seemed to fix it.
