### ISSUE TITLE
jpm sign times out for listed + full review add-ons

### ISSUE THREAD

**Issue by kumar303** [mozilla-jetpack/jpm#407]
To reproduce:

- submit an add-on to AMO and make it listed and request a full review
- get the initial add-on approved
- create a new version
- run `jpm sign` to auto-update the new version

This always ends in a time-out, with the following output:

````
$ jpm sign --api-key ... --api-secret ... --api-url-prefix http://olympia.dev/api/v3 --xpi ~/tmp/addons/scratch1/\@scratch1-0.0.4.xpi
JPM [info] Signing XPI: /Users/kumar/tmp/addons/scratch1/@scratch1-0.0.4.xpi
Validating add-on [......................................................................................................................................................................................]
JPM [error] FAIL
Error: Validation took too long to complete; last status: {"active":false,"url":"http://olympia.dev/api/v3/addons/%40scratch1/versions/0.0.4/uploads/256ab54aeb8f4163a264c57fb32848e4/","files":[{"hash":"sha256:6aab8ba9f66388e0e804d947c66f9a28ec8e0f595612a774ec6858959585640e","signed":false,"download_url":"http://olympia.dev/api/v3/file/132/scratch_1-0.0.4-fx+an.xpi?src=api"}],"passed_review":false,"pk":"256ab54aeb8f4163a264c57fb32848e4","processed":true,"reviewed":false,"valid":true,"validation_results":{"errors":0,"success":true,"warnings":0,"compatibi...
    at null._onTimeout (/Users/kumar/dev/jpm/lib/amo-client.js:151:14)
    at Timer.listOnTimeout (timers.js:110:15)
````

This is because the file will always require manual review since listed + full review gives it a side-loading certificate

**Comment by kumar303** [comment]
I think this would also be reproducible by submitting an unlisted add-on and checking the box for 'this will be bundled with an installer'

**Comment by kumar303** [comment]
This wasn't the right solution because it broke other things. See https://github.com/mozilla-jetpack/jpm/pull/413

**Comment by kumar303** [comment]
When the API changes from https://github.com/mozilla/olympia/pull/1041 are live (ETA: Dec 10, 2015), this patch should resolve the issue https://github.com/mozilla-jetpack/jpm/pull/415 I'll leave this open until then.

**Comment by kumar303** [comment]
This went out on Dec 10, 2015, as you can see from the tag: https://github.com/mozilla/olympia/commit/9b4d02927e078aa68fc343b356a2d517e2a7b5f1

I can't test it on prod because it would require fiddling with a listed add-on but it should be fixed.
