### ISSUE TITLE
jpm sign yields a timeout error

### ISSUE THREAD

**Issue by nikolas** [mozilla-jetpack/jpm#464]
I signed version 0.1.5 of my mediathread extension successfully yesterday, but today, with version 0.1.6, I got this timeout error:

```
$ jpm sign --api-key <user> --api-secret <secret>
Creating XPI
JPM [info] XPI created at /tmp/tmp-unsigned-xpi-1116612PbrnMQFpLu/@mediathread-firefox-prerelease-0.1.6.xpi (186ms)
Created XPI at /tmp/tmp-unsigned-xpi-1116612PbrnMQFpLu/@mediathread-firefox-prerelease-0.1.6.xpi
JPM [info] Created XPI for signing: /tmp/tmp-unsigned-xpi-1116612PbrnMQFpLu/@mediathread-firefox-prerelease-0.1.6.xpi
Validating add-on [............................................................................................................................]JPM [error] FAIL
Error: Validation took too long to complete; last status: {"active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/%40mediathread-firefox-prerelease/versions/0.1.6/uploads/8972858d81fd481399cc4f28057675a0/","files":[],"passed_review":false,"pk":"8972858d81fd481399cc4f28057675a0","processed":true,"reviewed":false,"valid":true,"validation_results":{"errors":0,"success":false,"warnings":15,"compatibility_summary":{"notices":0,"errors":0,"warnings":0},"passed_auto_validation":false,"ending_tier":5,"messages":[{"ignored":fals...
    at null._onTimeout (/home/nnyby/node_modules/jpm/lib/amo-client.js:174:14)
    at Timer.listOnTimeout (timers.js:92:15)
```

I tried the command again and got the same error.

**Comment by andymckay** [comment]
This isn't a jpm problem, rather an AMO problem. Which is being tracked in mozilla/olympia#1244, the time out message is clear, I'm not sure what else there is to do here.

**Comment by nikolas** [comment]
Alright, thanks.

For the record, my third `jpm sign` attempt was successful.
