### ISSUE TITLE
Is it possible to require jpm as a module?

### ISSUE THREAD

**Issue by arieljannai** [mozilla-jetpack/jpm#476]
I want to use it inside my program, but it's not working the easy way.
I guess it's only suitable for global use?

**Comment by kumar303** [comment]
Yes, you can require jpm as a module. Here is a test:
````
$ npm install jpm
...
$ node
> var sign = require("jpm/lib/sign");
undefined
> sign.signCmd();
{ state: 'pending' }
> JPM [error] FAIL
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at Object.validateProgram (/Users/kumar/tmp/jpm-test/node_modules/jpm/lib/cmd.js:40:10)
    at /Users/kumar/tmp/jpm-test/node_modules/jpm/lib/sign.js:131:17
    at init (/Users/kumar/tmp/jpm-test/node_modules/when/lib/makePromise.js:39:5)
    at new Promise (/Users/kumar/tmp/jpm-test/node_modules/when/lib/makePromise.js:27:53)
    at Function.promise (/Users/kumar/tmp/jpm-test/node_modules/when/when.js:98:10)
    at Object.signCmd (/Users/kumar/tmp/jpm-test/node_modules/jpm/lib/sign.js:130:15)
    at repl:1:6
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
````
You will need to read the source to anything useful with it. For example: https://github.com/mozilla-jetpack/jpm/blob/master/lib/sign.js#L126
