### ISSUE TITLE
Error: ENOTEMPTY: directory not empty, rmdir

### ISSUE THREAD

**Issue by akarineb** [mozilla-jetpack/jpm#529]
I'm trying to sign my extension mozilla with jpm but is always giving the same mistake in xpi

"JPM [error] FAIL
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\ANAKAR~1\AppData\Local\Temp\tmp-extracted-xpi-6604RrKjbXCVw94C\modules'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:763:18)
    at _rmdirRecursiveSync (C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\node_modules\tmp\lib\tmp.js:285:10)
    at Object._cleanupCallback [as remove] (C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\node_modules\tmp\lib\tmp.js:409:5)
    at C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\lib\utils.js:170:18
    at tryCatchReject (C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:804:4)
    at Fulfilled.when (C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:592:4)
    at Pending.run (C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:483:13)
    at Scheduler._drain (C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\Scheduler.js:62:19)"

Does anyone know how to fix ?
My operating system is Windows 10

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to file a bug. I feel like we fixed this one in jpm 1.0.5 by upgrading the tmp module (I think it was https://github.com/raszi/node-tmp/issues/35). What version of jpm are you running? Maybe I'm not thinking of the same bug.

**Comment by akarineb** [comment]
@kumar303 
I'm using version 1.0.7 . The question is already signed other xpi and everything went well , only one of them I'm having this problem .

**Comment by kumar303** [comment]
Huh, ok. If possible, could you provide the source of the add-on that causes this error?

**Comment by akarineb** [comment]
from what source are you talking about ?

**Comment by kumar303** [comment]
I was talking about the directory of code for your add-on (containing your package.json). This would allow us to reproduce the error since there is some specific file causing the bug.

**Comment by kumar303** [comment]
What prompted you to close the issue? Did the problem go away for you with a more recent version of `jpm`?

**Comment by akarineb** [comment]
My problem has changed. In fact I do not understand well what is package.json . I know it is created by jpm init command. But do not understand that when I create it or what it is for. I'm having trouble signing in the process of my add-on , some things are still very complicated for me.

**Comment by akarineb** [comment]
But as I said, now I'm having a new problem. I decided to redo the whole process of signing my add-on , have 3 xpi type 2 and a general xpi type 32. All type 2 xpi were signed without any problem and pass on all validation tests when I try to send them separately. But when I try to sign or send my general xpi type 32 (containing 3 xpi type 2 more or install.rdf ) always appears the same error: "I'm trying to sign my add-on , I have three type 2 xpi that are packaged in a kind of xpi 32. These three xpi have been signed by jpm . The problem is that when I 'm going to sign or try to send my type 32 xpi always failed validation appears the error " Sub -package must be signed. Error: Add-ons which contain sub-packages must have all sub-packages signed before uploading." I've tried several things and redid the signing process from the start several times but is not working.
I've tried several things but I can not find any solution , I believe the package.json has something to do with this problem, but have no idea how to fix .

I'm signing by jpm . The version is the most current . My system is Windows 10 and the files of my add-on is stored in the main local disk desktop.

**Comment by kumar303** [comment]
> Sub -package must be signed

This means that there is another XPI nested inside your source code. I think you can fix this by removing all XPI files from your source directory (including any nested directories) then running `jpm sign` again.

**Comment by akarineb** [comment]
I own 3 xpi and all are duly signed , already remade several times the signing process to ensure this. But still, when I sign my xpi that stores the three other gives this error.

**Comment by kumar303** [comment]
Oh, you are nesting XPIs within an XPI on purpose? If you can upload an example of the XPI that fails when you try to sign it then I can take a look. You could also email it to me to keep the source private: kmcmillan@mozilla.com

**Comment by kumar303** [comment]
Sorry, I can't seem to find it (I looked in spam folders). What was the subject of the email?

**Comment by akarineb** [comment]
I sent again with the subject " Sub -package must be signed "

**Comment by kumar303** [comment]
Huh, odd. I am not receiving it. You could send it to my other address: kumar.mcmillan@gmail.com

Sorry for the hassle. It sounds like one of the sub-packages is truly unsigned (it might be hidden somewhere) but I'd have to look at the source to be sure.
